// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wrqifwfgtbqlicxbabfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndycWlmd2ZndGJxbGljeGJhYmZ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU4NTY0MDIsImV4cCI6MjA3MTQzMjQwMn0.kWqf30aHeqVrYDtTdUStxOM2UVZbAwV2_A5gYQKBQrA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});